### PR TITLE
Update CODEOWNERS and update components to match GEOSgcm v10.22.1

### PR DESCRIPTION
**Pull request by mathomp4**
This PR updates the `CODEOWNERS` file so that PR approvals here are less onerous. Only the CI and weird CCPP/UFS directories will need approval from non-aerosol team members.

NOTE: I think this will not truly take effect until this change is in `main` due to the way GitHub works. (Only the `CODEOWNERS` on `main` matters to GitHub. Annoying, but it's how they do things.)

---

ETA: I've also updated `components.yaml` to match that of GEOSgcm v10.22.1. The main thing is to get MAPL 2.19.0 which is needed for the new AGC code that is in `develop`.

### CODE REVIEW

**Review by adarmenov — APPROVED** [review]

**Review by tclune — APPROVED** [review]

**Review by amdasilva — CHANGES_REQUESTED** [review]
Please add @amdasilva to any directory that does not include aerosol-team.

**Comment by mathomp4** [comment]
> Please add @amdasilva to any directory that does not include aerosol-team.

Done.

**Review by adarmenov — APPROVED** [review]

**Comment by mathomp4** [comment]
Apologies to @adarmenov but he might need a re-approve. I'm going to try and fix the CI. I think I know the issue.

**Review by adarmenov — COMMENTED** [review]
@mathomp4 - there are also changes to fixture tags/versions, i.e. the PR is not only update CODEOWNERS(?).

**Comment by mathomp4** [comment]
> @mathomp4 - there are also changes to fixture tags/versions, i.e. the PR is not only update CODEOWNERS(?).

Thanks. I updated the title to the PR to reflect that.

**Review by adarmenov — DISMISSED** [review]

**Review by amdasilva — APPROVED** [review]
Looks good.

**Review by tclune — APPROVED** [review]

**Pull request merged**
