### PR TITLE
Set `k` in `SUvolcanicEmissions` to be integer

### PR DESCRIPTION
**Pull request by zmoon**
This addresses these warnings:

```
GOCART/Process_Library/GOCART2G_Process.F90:5787:27:

 5787 |             z1 = hghte(i,j,k-1) ! geopotential altitude at gridbox top
      |                           1
Warning: Legacy Extension: REAL array index at (1)
GOCART/Process_Library/GOCART2G_Process.F90:5824:20:

 5824 |             so2(i,j,k) = so2(i,j,k) + deltaSO2v*cdt*grav/delp(i,j,k)
      |                    1
Warning: Legacy Extension: REAL array index at (1)
GOCART/Process_Library/GOCART2G_Process.F90:5824:66:

 5824 |             so2(i,j,k) = so2(i,j,k) + deltaSO2v*cdt*grav/delp(i,j,k)
      |                                                                  1
Warning: Legacy Extension: REAL array index at (1)
GOCART/Process_Library/GOCART2G_Process.F90:5824:33:

 5824 |             so2(i,j,k) = so2(i,j,k) + deltaSO2v*cdt*grav/delp(i,j,k)
      |                                 1
Warning: Legacy Extension: REAL array index at (1)
GOCART/Process_Library/GOCART2G_Process.F90:5786:12:

 5786 |          do k = km, 1, -1
      |            1
Warning: Deleted feature: Loop variable at (1) must be integer
```

### CODE REVIEW

**Review by jrjoshi1 — DISMISSED** [review]

**Comment by zmoon** [comment]
Do you want me to add something to the changelog?

**Comment by vbuchard** [comment]
> Do you want me to add something to the changelog?

Yes, please if you don't mind. Also FYI in case of future PR: the PR merge needs to happen in the develop branch (we were able to move it manually) and labels ( 0-diff, non 0 diff, bug...) are also required during the checks. Thanks

**Comment by zmoon** [comment]
> Also FYI in case of future PR: the PR merge needs to happen in the develop branch (we were able to move it manually) and labels ( 0-diff, non 0 diff, bug...) are also required during the checks.

Sorry for targeting the wrong branch!

As outside contributor I can't apply labels. I was curious about the 0-diff meaning though. If it's about the program/tests producing the same results as before, I would expect this PR to be 0-diff?

Also the validate-YAML Workflow seems to be broken (I don't see an open issue though?).

**Comment by vbuchard** [comment]
> > Also FYI in case of future PR: the PR merge needs to happen in the develop branch (we were able to move it manually) and labels ( 0-diff, non 0 diff, bug...) are also required during the checks.
> 
> Sorry for targeting the wrong branch!
> 
> As outside contributor I can't apply labels. I was curious about the 0-diff meaning though. If it's about the program/tests producing the same results as before, I would expect this PR to be 0-diff?
> 
> Also the validate-YAML Workflow seems to be broken (I don't see an open issue though?).

I added the 0-diff label. No worries for the yaml test, Matt introduced a fix in a previous PR (we usually go in order for merging). My guess is as soon as we will merge the previous PR, we will be able to merge this one.

**Review by jrjoshi1 — APPROVED** [review]

**Comment by zmoon** [comment]
Thanks for merging this. Do you have an estimate of when the next stable release might be?

**Comment by vbuchard** [comment]
> Thanks for merging this. Do you have an estimate of when the next stable release might be?

We merged quite a lot of PRs into develop, so @jrjoshi1 is going to perform several testing. Hopefully we'll have a release in the next coming weeks.

**Pull request merged**
