### PR TITLE
Fix optical properties computation

### PR DESCRIPTION
**Pull request by rmontuoro**
This PR introduces changes addressing issue #64. 

`aerosol_monochromatic_optics_wavelength`s are now assumed to be provided in units of `nm` and internally converted to `m` for proper lookup using the diagnostic Mie table.

`aerosol_monochromatic_optics_wavelength` could be renamed as `aerosol_monochromatic_optics_wavelength_in_nm` for consistency with other configuration labels.

### CODE REVIEW

**Review by adarmenov — APPROVED** [review]

**Review by tclune — APPROVED** [review]
Am approving, but am hoping to get confirmation from @amdasilva before merging.

**Comment by tclune** [comment]
Mentioning to @pcolarco in case it impacts any resource files he might be using.  (Probably not using 2G yet ...)

**Comment by mathomp4** [comment]
For @rmontuoro's benefit, the merge from `develop` was to remove Elliot as a codeowner.

**Comment by mathomp4** [comment]
I tested this branch with GEOSgcm and it was zero-diff (of course) for GOCART Legacy. But good to make sure!

**Comment by mathomp4** [comment]
@rmontuoro I'm blocking this for now as @tclune and I have some questions for @amdasilva about what you've pointed out. There are some inconsistencies we see here.

**Comment by mathomp4** [comment]
Uh. Hmm. Okay. Label enforcer isn't working? Hmm. Time to fix that!

**Comment by rmontuoro** [comment]
> @rmontuoro I'm blocking this for now as @tclune and I have some questions for @amdasilva about what you've pointed out. There are some inconsistencies we see here.

@mathomp4 - Please let me know if I can help from our side. We have carried out test runs with these changes and the results look good so far.

**Comment by tclune** [comment]
The inconsistencies are across the gocart children in terms of names of resource parameters, not the answers per se.

**Comment by mathomp4** [comment]
> > @rmontuoro I'm blocking this for now as @tclune and I have some questions for @amdasilva about what you've pointed out. There are some inconsistencies we see here.
> 
> @mathomp4 - Please let me know if I can help from our side. We have carried out test runs with these changes and the results look good so far.

@rmontuoro If you have a chance, can you try out branch `feature/mathomp4/nanometer-consistency` and see if it provides the same answers as this branch? 

It's a branch off of this branch where I did [a bunch of sed's to try and get things consistent](https://github.com/GEOS-ESM/GOCART/compare/bugfix/rmontuoro/diag-mie-wavelengths...feature/mathomp4/nanometer-consistency). It might not be how we want to go with this, but if it is, I can make a PR into your branch

**Comment by rmontuoro** [comment]
@mathomp4 - I've verified that your [changes](https://github.com/GEOS-ESM/GOCART/compare/bugfix/rmontuoro/diag-mie-wavelengths...feature/mathomp4/nanometer-consistency) produce bitwise identical results to this PR.

**Comment by mathomp4** [comment]
> @mathomp4 - I've verified that your [changes](https://github.com/GEOS-ESM/GOCART/compare/bugfix/rmontuoro/diag-mie-wavelengths...feature/mathomp4/nanometer-consistency) produce bitwise identical results to this PR.

@rmontuoro Thanks! Once we get direction, I'll make a PR from my branch to yours. Hopefully we hear about that soon!

**Comment by mathomp4** [comment]
@rmontuoro Update. There is GMAO-side update to `develop` coming soon which might render this PR (and #67) moot. It's validated-science changes from @pcolarco that as far as I can tell actually fixes the same problems you saw here and actually does the cleanup I did in #67. 

It's done in a slightly different way, but as far as I can see, it is equivalent. We might want you to try that branch once we make sure the merge of your UFS code into it was done in a GEOS safe way.

**Comment by mathomp4** [comment]
Closing in favor of #74

**Pull request closed without merging**
