### PR TITLE
Sync tag sdr_v2.1.2.6 into develop

### PR DESCRIPTION
**Pull request by sdrabenh**
@amdasilva this PR captures the changes made to accommodate Krok. Please see the owners of the commits below for questions. There were several merge conflicts, so hopefully my hand-merges are correct. I'm unsure at this point whether this PR is 0-diff or not. I would have to test this to be sure. In the meantime I will mark it as both.

### CODE REVIEW

**Review by amdasilva — DISMISSED** [review]
It looks good, but see #231 regarding architecture violation (which has been introduced prior to this PR).

**Comment by sdrabenh** [comment]
> It looks good, but see #231 regarding architecture violation (which has been introduced prior to this PR).

I will raise this with @wmputman on Monday

**Comment by mathomp4** [comment]
@sdrabenh I updated the `CHANGELOG.md` in this branch to remove all the references to `sdr_*` tags as well as remove redundant entries (e.g., GOCART Data).

**Comment by mathomp4** [comment]
Also just fixed a bad-merge line causing a CI failure.

**Comment by mathomp4** [comment]
Update: I've added the bugfix I talk about in #234 here as well as I think it is a bug.

**Pull request merged**
