### PR TITLE
Feature/aelakkra/r21c updates

### PR DESCRIPTION
**Pull request by elakkraoui**

### CODE REVIEW

**Comment by mathomp4** [comment]
Okay. This PR might need a bit of massaging. The issue is this PR cannot go into `main`. `main` is GOCART2 now and can't go back. 

What I think we will need to do is make a release branch from v1.0.1. You can see the differences against v1.0.1 here:

https://github.com/GEOS-ESM/GOCART/compare/v1.0.1...feature/aelakkra/r21c_updates

I can work with @amdasilva or whoever to get this done. Not hard, just a consequence of GOCART moving into 2G land, so any PRs and releases for GOCART1 need to be done on a different branch.

cc: @tclune

**Comment by amdasilva** [comment]
We cannot merge v1.0.1 into "Main" as "Main" has moved on to GOCART 2G.  Please make the pull request to branch "release/1.0".  BTW, update the CHANGELOG, this is not a "hotfix" as we do not intend to port it to the main development line.

Please merge branch release/1.0 into your branch and make another PR. Once merged it back into branch "release/1.0" I will issue the official release v1.0.2.

**Review by amdasilva — CHANGES_REQUESTED** [review]
Please make PR to branch release/1.0

**Comment by amdasilva** [comment]
Matt,

    I closed this PR, see my comments. The PR needs to be for branch release/1.0 as this is not a hotfix.

        Arlindo

From: Matthew Thompson ***@***.***>
Reply-To: GEOS-ESM/GOCART ***@***.***>
Date: Friday, March 18, 2022 at 9:36 AM
To: GEOS-ESM/GOCART ***@***.***>
Cc: "DA SILVA, ARLINDO M (GSFC-6101)" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/GOCART] Feature/aelakkra/r21c updates (PR #125)


Okay. This PR might need a bit of massaging. The issue is this PR cannot go into main. main is GOCART2 now and can't go back.

What I think we will need to do is make a release branch from v1.0.1. You can see the differences against v1.0.1 here:

v1.0.1...feature/aelakkra/r21c_updates<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGOCART%2Fcompare%2Fv1.0.1...feature%2Faelakkra%2Fr21c_updates&data=04%7C01%7Carlindo.m.dasilva%40nasa.gov%7Cacaa1cb473b444431dd008da08e4445c%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637832073738763697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lP%2FXU8RuW2h38qNqV%2FlZumNLr3S8vny500aC8S%2Becno%3D&reserved=0>

I can work with @amdasilva<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famdasilva&data=04%7C01%7Carlindo.m.dasilva%40nasa.gov%7Cacaa1cb473b444431dd008da08e4445c%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637832073738763697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ykotZPbCh0Ct5LbGqXfCh9vcFXYSAUmduobGsPBooOc%3D&reserved=0> or whoever to get this done. Not hard, just a consequence of GOCART moving into 2G land, so any PRs and releases for GOCART1 need to be done on a different branch.

cc: @tclune<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftclune&data=04%7C01%7Carlindo.m.dasilva%40nasa.gov%7Cacaa1cb473b444431dd008da08e4445c%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637832073738763697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=r0%2FjUZFbnUQhwdRfyHQDGy5%2BO5aPwFrAlqfUayBXzAY%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGOCART%2Fpull%2F125%23issuecomment-1072417827&data=04%7C01%7Carlindo.m.dasilva%40nasa.gov%7Cacaa1cb473b444431dd008da08e4445c%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637832073738763697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Y8IZhahTypEPzy9kAbDe8PDkZAW6UMO4D5vbak6urjQ%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAH5LTY7MX3K65TXQML2B5PLVASBERANCNFSM5RBZAPIA&data=04%7C01%7Carlindo.m.dasilva%40nasa.gov%7Cacaa1cb473b444431dd008da08e4445c%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637832073738763697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DWgJoE7Atbi6UBRTooRDt90w0MZ%2FOZKf68qREW0wTm0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Carlindo.m.dasilva%40nasa.gov%7Cacaa1cb473b444431dd008da08e4445c%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637832073738763697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SaY2Gt6mA2S0Dv2PcoGUcp0zky%2FlOQ%2BTJmy9kBQUTKw%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Carlindo.m.dasilva%40nasa.gov%7Cacaa1cb473b444431dd008da08e4445c%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637832073738763697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=N%2F4ps3nJDUZuu5PKscvdFtdxK3u1H0kFDBY%2F3KtG9MQ%3D&reserved=0>.

**Pull request closed without merging**
