### PR TITLE
Add GEOSgcm Build to CI

### PR DESCRIPTION
**Pull request by mathomp4**
This adds a GEOSgcm CI build to the GOCART repo

### CODE REVIEW

**Comment by mathomp4** [comment]
Deleted the wrong thing. I need to fix this...

**Comment by mathomp4** [comment]
@WilliamJamieson Hmm. Well, I think it's possible your GEOSgcm branch is out of date in some of the subrepos...

**Comment by mathomp4** [comment]
Seems to have worked. Though the GCM build depends on the GEOSgcm branch used staying the same, of course

**Review by bena-nasa — APPROVED** [review]

**Comment by mathomp4** [comment]
Closing as #20 pulled this in.

**Pull request closed without merging**
