### PR TITLE
Fixes #165. Add SetVM to UFS Aerosol Cap

### LINKED ISSUE #165: Add SetVm in ESMF/UFS/Aerosol_Cap.F90 for ESMF managed threading capability.
We are adding the ESMF managed threading in UFS weather model. Two lines of code need to be added to ESMF/UFS/Aerosol_Cap.F90.
```
diff --git a/ESMF/UFS/Aerosol_Cap.F90 b/ESMF/UFS/Aerosol_Cap.F90
index ad6dc04..d44ab1f 100644
--- a/ESMF/UFS/Aerosol_Cap.F90
+++ b/ESMF/UFS/Aerosol_Cap.F90
@@ -6,6 +6,7 @@ module Aerosol_Cap
   use NUOPC
   use NUOPC_Model, only : &
     NUOPC_ModelGet, &
+    SetVM,  &
     model_routine_SS            => SetServices,          &
     model_routine_Run           => routine_Run,          &
     model_label_Advance         => label_Advance,        &
@@ -75,6 +76,7 @@ module Aerosol_Cap
   private

   public :: SetServices
+  public :: SetVM

 contains
```

Could these two lines be added in the GOCART code? We expect no impact on the GOCART that does not use the ESMF managed threading. Thanks.

### PR DESCRIPTION
**Pull request by mathomp4**
Closes #165 

Per request of @junwang-noaa in #165, this adds `SetVM` to the UFS Aerosol Cap.

As long as this compiles, it should be fine for GEOS. We don't compile the UFS code, so it's a no-op for us.

### CODE REVIEW

**Review by atrayano — APPROVED** [review]
The changes look safe

**Comment by junwang-noaa** [comment]
@tclune We are waiting for this change to commit the ESMF managed threading in UFS. May I ask when this PR will be committed? Thank you!

**Comment by tclune** [comment]
@junwang-noaa The gatekeeper is on vacation through July.   We will check with someone in his group to see if she feels qualified to merge this in ...

**Comment by junwang-noaa** [comment]
@tclune Thanks a lot!

**Review by vbuchard — APPROVED** [review]

**Comment by junwang-noaa** [comment]
@vbuchard @tclune  Thanks!

**Pull request merged**
