### PR TITLE
Fix memory corruption in nitrate component

### PR DESCRIPTION
**Pull request by rmontuoro**
This PR introduces changes to prevent memory corruption occurring in GOCART's nitrate component when diagnostic variables for settling (`NISD`) and wet removal (`NH3WT`, `NH4WT`) are enabled.

The memory corruption was traced back to allocated arrays being passed to subroutines expecting a pointer array argument (see example below):

```
-    allocate(fluxout, mold=lwi, __STAT__)
 !  Nitrate bin 1 - settles like ammonium sulfate (rhflag = 3)
     rhflag = 3
-    fluxout = 0.
+    nullify(flux_ptr)
+    if (associated(NISD)) flux_ptr => NISD(:,:,1)
     call Chem_SettlingSimpleOrig (self%km, self%klid, rhFlag, MAPL_GRAV, self%cdt, &
                                   1.e-6*self%radius(nNO3an1), self%rhop(nNO3an1), &
-                                  NO3an1, t, airdens, rh2, delp, zle, fluxout, rc)
-    if (associated(NISD)) NISD(:,:,1) = fluxout
+                                  NO3an1, t, airdens, rh2, delp, zle, flux_ptr, rc)
```
```
   subroutine Chem_SettlingSimpleOrig ( km, klid, flag, grav, cdt, radiusInp, rhopInp, &
                                        int_qa, tmpu, rhoa, rh, delp, hghte, &
                                        fluxout, rc, vsettleOut, correctionMaring )
   ...
! !OUTPUT PARAMETERS:
   real, pointer, dimension(:,:), intent(inout)  :: fluxout
```

Additionally, a minor change is included to set the correct intent for a dummy argument.

This PR is contingent on approval of PR #24.

### CODE REVIEW

**Review by tclune — APPROVED** [review]
It would be nice to have a more complete description of the bug that was fixed.   I stared a bit at the code, but did not see what was actually wrong with the additional version.    E.g., did the changes juts "move the symptoms" of some issue somewhere else?     

But I don't want the explanation to get in the way of the merge.

**Comment by rmontuoro** [comment]
> It would be nice to have a more complete description of the bug that was fixed. I stared a bit at the code, but did not see what was actually wrong with the additional version. E.g., did the changes juts "move the symptoms" of some issue somewhere else?
> 
> But I don't want the explanation to get in the way of the merge.

Some text was missing from my early description. I've added it back along with further details.

**Comment by tclune** [comment]
@rmontuoro Thanks.    I'm a bit surprised that this issue was not diagnosed by the compiler.    Might be time to ask Elliot to include occasional builds with the backup compiler which should find more of these.

I the fix might have been simpler.    There is no reason for the dummy arguments in the process library to be pointers.  That is  an artifact of a poor translation from the original F77 interfaces.   We have fixed some of those but a more pervasive change is called for.

**Comment by mathomp4** [comment]
This has a *lot* of file changes... should it?

**Comment by WilliamJamieson** [comment]
> This has a _lot_ of file changes... should it?

It has both PR #23 and #24 merged into it in addition to the changes it makes.

**Comment by rmontuoro** [comment]
> This has a _lot_ of file changes... should it?

@mathomp4 - As @WilliamJamieson pointed out, this PR also includes #24, which brings in a large number of changes. Hope this is OK, but I can resubmit a new PR with more focused changes.

**Comment by tclune** [comment]
I think we can take this PR as is, but going forward please try to isolate bug fixes as much as possible.   We're a bit sloppy but we tend to take a closer look at understanding bug fixes.   Reviews for non-fixes are quite variable in terms of thoroughness and tend to be more about style and extensibility.

**Comment by mathomp4** [comment]
> I think we can take this PR as is, but going forward please try to isolate bug fixes as much as possible. We're a bit sloppy but we tend to take a closer look at understanding bug fixes. Reviews for non-fixes are quite variable in terms of thoroughness and tend to be more about style and extensibility.

Almost. @rmontuoro would need to add his "if not Baselibs" update from #24 I think.

**Review by gmao-esherman — APPROVED** [review]
I have verified that these changes are zero-diff with the feature/esherman/gocart2g_develop_WilliamUpdate build

**Review by WilliamJamieson — APPROVED** [review]
My and Elliot's tests show that this is zero-diff.

**Comment by tclune** [comment]
Using super powers again.

**Pull request merged**
