### PR TITLE
Fix CMake circular dependencies for external use

### PR DESCRIPTION
**Pull request by mathomp4**
As found by @climbfuji, if you build GEOSgcm, you get three sets of CMake files for doing `find_package`: MAPL, GEOSgcm, and GOCART. This then causes circular dependencies as GOCART requires things "provided" by GEOSgcm and GEOSgcm requires GOCART.

So this PR tries to "detect" if GOCART is being built as a standalone project or as part of GEOS.

ETA: In tests trying to build GOCART with MAPL-as-library-from-spack, it was found that you need to protect against the chance MAPL is found as a library. Then you can't *add* MAPL as a new subdirectory as targets will be duplicated.

### CODE REVIEW

**Comment by mathomp4** [comment]
@climbfuji said this worked for him. So I'll undraft.

**Comment by rtodling** [comment]
I hope this can make up so 11.5.3 version of the model - very important for GEOS-JEDI development.

**Review by climbfuji — APPROVED** [review]
Thanks for thes updates @mathomp4 . This works fine for us (JCSDA)!

**Review by climbfuji — APPROVED** [review]
I don't understand these changes very well, but if it works it works!

**Review by vbuchard — APPROVED** [review]

**Pull request merged**
