### PR TITLE
Updates to support Spack

### PR DESCRIPTION
**Pull request by mathomp4**
This zero-diff PR has build system changes to support the use of Spack. Most of the changes just make the GEOS CMake look more like canonical CMake. GEOS previously couldn't support this, but it now can.

See https://github.com/GEOS-ESM/GEOSgcm/issues/387 for overall issue.

### CODE REVIEW

**Comment by mathomp4** [comment]
Scott has pulled in https://github.com/GEOS-ESM/GEOSgcm/pull/388. Therefore, I feel safe undrafting this.

**Review by adarmenov — DISMISSED** [review]

**Review by tclune — APPROVED** [review]
CMake changes good.

**Review by amdasilva — APPROVED** [review]
Looks good to me...

**Review by amdasilva — APPROVED** [review]
Good enough to me...

**Review by tclune — APPROVED** [review]

**Pull request merged**
