### PR TITLE
Merge develop into main

### PR DESCRIPTION
**Pull request by mathomp4**
This gets the CI and other updates from the handmerge PR into main.

### CODE REVIEW

**Comment by mathomp4** [comment]
Oh boy...that was a lot more differences than I was thinking. I might not do this just yet...

**Comment by mathomp4** [comment]
@tclune @WilliamJamieson @gmao-esherman What are your thoughts on bringing `develop` into `main` now? I mainly wanted to do it to get the fixes I made during the handmerge (#22) back to `main`. But this would bring all of the 2G work into `main`. 

We know that https://github.com/GEOS-ESM/GEOSgcm/pull/257 by @WilliamJamieson sparses out GOCART2G, etc. so it's "equivalent" to current GOCART.

**Comment by mathomp4** [comment]
I am going to do a build and test with this branch. Make sure it is still zero-diff to GEOSgcm stock.

**Comment by mathomp4** [comment]
I just did some tests with this and GEOSgcm built and is zero-diff with both actual (MERRA2) and climatological (GOCART.data) aerosols.

**Review by WilliamJamieson — APPROVED** [review]
In light of your zero-diff test, I think I am fine with this.

**Review by gmao-esherman — APPROVED** [review]
@mathomp4 has verified zero-diff!

**Comment by tclune** [comment]
I would have said to wait until 2G is ready to become the default for GOCART.  Merging now slightly complicates things if legacy GOCART needs a hotfix in the mean time.    But such is life.

**Pull request merged**
