### PR TITLE
fix bug in getAerosolSum

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
@amdasilva , This is for the issue #136.  I am not sure if it a good fix. Please verify it.

### CODE REVIEW

**Comment by mathomp4** [comment]
@weiyuan-jiang Do you know if this is a zero-diff change?

**Comment by weiyuan-jiang** [comment]
@mathomp4 It is supposed not. But if this subroutine is not used in the benchmark, then it is zero-diff

**Review by adarmenov — DISMISSED** [review]

**Review by amdasilva — APPROVED** [review]
Looks good.

**Review by vbuchard — APPROVED** [review]
Looks good

**Pull request merged**
