### PR TITLE
Handmerge main into develop

### PR DESCRIPTION
**Pull request by mathomp4**
This is a handmerge to get `main` into `develop`. I might ping @WilliamJamieson to try this branch out. Maybe this was a bad idea...

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
@mathomp4 this does not look right. I'll look into how to fix it.

**Comment by mathomp4** [comment]
Making this non-draft. We'll probably need @gmao-esherman to test and make sure develop didn't go kaboom. I can work with @gmao-esherman on this if he'd like (I think I know what GitHub is doing in the background, so I know what commands to run)

**Review by tclune — APPROVED** [review]

**Comment by WilliamJamieson** [comment]
@gmao-esherman, can you test that this will not break any of your current work?

**Comment by gmao-esherman** [comment]
> @gmao-esherman, can you test that this will not break any of your current work?

Yes, of course. I think I will take @mathomp4 up on his offer though!

**Review by gmao-esherman — APPROVED** [review]
@mathomp4 has tested this branch and verified that it zero-diffs with legacy gocart.

**Pull request merged**
