### PR TITLE
Feature/wjiang/bugs with namechanging

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
fix bugs
1) more hard-coded name changes
2) MieQuery.H,  shape of not present variables.

NOTE: You should also get https://github.com/GEOS-ESM/GEOSgcm_App/pull/317 so that HISTORY is happy

### CODE REVIEW

**Review by tclune — DISMISSED** [review]
My one comment - really just a suggestion to @amdasilva , it may be useful to introduce a method on the private state that does the operation `trim(comp_name)//var_name`.   Would not make the expressions much shorter, but would make the intent a bit more clear.

**Comment by weiyuan-jiang** [comment]
This PR should also address issue #129

**Comment by weiyuan-jiang** [comment]
> [internal](https://github.com/GEOS-ESM/GOCART/pull/138/files#diff-f76b47fb134011adf4b35f41768a9148c1da718e5207eea6e1412bd9ab388b88R1087) is misspelled in the comment.

fixed

**Review by adarmenov — APPROVED** [review]

**Review by adarmenov — APPROVED** [review]

**Comment by bena-nasa** [comment]
@amdasilva @adarmenov 
Can someone please please just merge this already. Develop is broken until this goes in. It makes it very hard for every else to do development if Develop doesn't work.

**Comment by adarmenov** [comment]
> @amdasilva @adarmenov We need to get this merged (and the corresponding PR in GEOSgcm_App) Develop is broken until this goes in. It makes it very hard for every else to do development if Develop doesn't work.

@bena-nasa FWIW I've reviewed and approved the PR twice.

**Comment by bena-nasa** [comment]
> > @amdasilva @adarmenov We need to get this merged (and the corresponding PR in GEOSgcm_App) Develop is broken until this goes in. It makes it very hard for every else to do development if Develop doesn't work.
> 
> @bena-nasa FWIW I've reviewed and approved the PR twice.

@amdasilva could you please merge this? This has been sitting here for a month.

**Review by amdasilva — APPROVED** [review]
Looks good.

**Review by vbuchard — APPROVED** [review]
Looks good.

**Pull request merged**
