### PR TITLE
Fixes optional rc bugs

### LINKED ISSUE #9: RC codes in Process_Library
There are many optional return codes (`rc`) in the Process_Library that are directly assigned to without checking if the `rc` is present. If one calls a routine without specifying the optional `rc` this will cause a runtime error (Segmentation fault).

### PR DESCRIPTION
**Pull request by WilliamJamieson**
The process library `GOCART2G_Process.F90` had several instances of an optional `rc` being set without first checking if it is present. This fixes those instances which resolves #9.

### CODE REVIEW

**Comment by mathomp4** [comment]
Note: The CI failure is because the CircleCI config file is only on `develop` and not on `main` (or this branch) yet.

**Comment by gmao-esherman** [comment]
Can we use the ___EXAMPLE__ commands? I thought this was MAPL related.

**Comment by WilliamJamieson** [comment]
@gmao-esherman, you can use any of the macros defined at the top of the file (lines 1-7). They happen to imitate the MAPL ones.

**Review by tclune — CHANGES_REQUESTED** [review]
I think these changes are not necessary.   The process library does not use optional output for rc.

**Comment by tclune** [comment]
This PR requires a discussion.

**Comment by WilliamJamieson** [comment]
Closing due offline discussion between @tclune and @amdasilva

**Pull request closed without merging**
