### PR TITLE
Use nanometers consistently and update resource name

### PR DESCRIPTION
**Pull request by mathomp4**
This updated the branch of @rmontuoro for consistency. Making a draft to keep it here.

### CODE REVIEW

**Comment by mathomp4** [comment]
@rmontuoro I think we are good with this if you are. So if you approve here, we can merge this into your branch and then pull your branch into develop and then that into main and then release!

**Review by rmontuoro — APPROVED** [review]
I approve the changes, with the following comment:

Since all components read settings for optical properties from `universal_cfg`, which is set by the GOCART2G component, such settings are only required to be present in `GOCART2G_GridComp.rc` and should not be included in the remaining GridComp rc files.

**Comment by mathomp4** [comment]
> I approve the changes, with the following comment:
> 
> Since all components read settings for optical properties from `universal_cfg`, which is set by the GOCART2G component, such settings are only required to be present in `GOCART2G_GridComp.rc` and should not be included in the remaining GridComp rc files.

@rmontuoro So what is an example of a line I should remove? I can then do that for you

**Comment by rmontuoro** [comment]
@mathomp4 - As far as the UFS is concerned, we only need to have the following lines in `GOCART2G_GridComp.rc`:
```
wavelengths_for_profile_aop_in_nm: 470 550 870
wavelengths_for_vertically_integrated_aop_in_nm: 470 550 670 870
aerosol_monochromatic_optics_wavelength: 470 550 670 870
```

None of these lines is needed for all other gridded components, nor are settings for `n_channels` and `r_channels` (see patch below as an example). I don't know if these changes may affect GEOS-5, though. 

```
CA2G_GridComp_CA.bc.rc
--- CA2G_GridComp_CA.bc.rc  2021-07-02 17:02:56.000000000 +0000
+++ CA2G_GridComp_CA.bc.rc      2021-08-03 03:24:03.000000000 +0000
@@ -7,9 +7,6 @@
 aerosol_radBands_optics_file: ExtData/optics/opticsBands_BC.v1_3.RRTMG.nc

 aerosol_monochromatic_optics_file: ExtData/monochromatic/optics_BC.v1_3.nc
-aerosol_monochromatic_optics_wavelength: 4.7e-7 5.5e-7 6.7e-7 8.7e-7 ! units: nm
-wavelengths_for_vertically_integrated_aop_in_nm: 470 550 670 870
-n_channels: 4

 # Heights [m] of LTO, CDS and CRS aviation emissions layers
 aviation_vertical_layers: 0.0 100.0 9.0e3 10.0e3
CA2G_GridComp_CA.br.rc
--- CA2G_GridComp_CA.br.rc  2021-07-02 17:20:57.000000000 +0000
+++ CA2G_GridComp_CA.br.rc      2021-08-03 03:24:23.000000000 +0000
@@ -5,10 +5,6 @@
 aerosol_radBands_optics_file: ExtData/optics/opticsBands_BRC.v1_5.RRTMG.nc

 aerosol_monochromatic_optics_file: ExtData/monochromatic/optics_BRC.v1_5.nc
-aerosol_monochromatic_optics_wavelength: 470 550 670 870 ! units: nm
-wavelengths_for_vertically_integrated_aop_in_nm: 470 550 670 870
-n_channels: 4
-r_channels: 4.7e-7 5.5e-7 6.7e-7 8.7e-7

 # Heights [m] of LTO, CDS and CRS aviation emissions layers
 aviation_vertical_layers: 0.0 100.0 9.0e3 10.0e3
CA2G_GridComp_CA.oc.rc
--- CA2G_GridComp_CA.oc.rc  2021-07-02 17:02:56.000000000 +0000
+++ CA2G_GridComp_CA.oc.rc      2021-08-03 03:24:31.000000000 +0000
@@ -5,9 +5,6 @@
 aerosol_radBands_optics_file: ExtData/optics/opticsBands_OC.v1_3.RRTMG.nc

 aerosol_monochromatic_optics_file: ExtData/monochromatic/optics_OC.v1_3.nc
-aerosol_monochromatic_optics_wavelength: 4.7e-7 5.5e-7 6.7e-7 8.7e-7 ! units: nm
-wavelengths_for_vertically_integrated_aop_in_nm: 470 550 670 870
-n_channels: 4

 # Heights [m] of LTO, CDS and CRS aviation emissions layers
 aviation_vertical_layers: 0.0 100.0 9.0e3 10.0e3
CAP.rc
DU2G_GridComp_DU.rc
--- DU2G_GridComp_DU.rc     2021-07-02 17:02:56.000000000 +0000
+++ DU2G_GridComp_DU.rc 2021-08-03 03:24:44.000000000 +0000
@@ -5,9 +5,6 @@
 aerosol_radBands_optics_file: ExtData/optics/opticsBands_DU.v15_3.RRTMG.nc

 aerosol_monochromatic_optics_file:ExtData/monochromatic/optics_DU.v15_3.nc
-aerosol_monochromatic_optics_wavelength: 4.7e-7 5.5e-7 6.7e-7 8.7e-7 ! units: nm
-wavelengths_for_vertically_integrated_aop_in_nm: 470 550 670 870
-n_channels: 4

 particle_radius_microns: 0.73 1.4 2.4 4.5 8.0

--- SS2G_GridComp_SS.rc     2021-07-02 17:02:56.000000000 +0000
+++ SS2G_GridComp_SS.rc 2021-08-03 03:25:06.000000000 +0000
@@ -5,9 +5,6 @@
 aerosol_radBands_optics_file: ExtData/optics/opticsBands_SS.v3_3.RRTMG.nc

 aerosol_monochromatic_optics_file: ExtData/monochromatic/optics_SS.v3_3.nc
-aerosol_monochromatic_optics_wavelength: 4.7e-7 5.5e-7 6.7e-7 8.7e-7 ! units: nm
-wavelengths_for_vertically_integrated_aop_in_nm: 470 550 670 870
-n_channels: 4

 particle_radius_microns: 0.079 0.316 1.119 2.818 7.772

SU2G_GridComp_SU.rc
--- SU2G_GridComp_SU.rc     2021-07-02 17:24:47.000000000 +0000
+++ SU2G_GridComp_SU.rc 2021-08-03 03:25:11.000000000 +0000
@@ -5,14 +5,11 @@
 aerosol_radBands_optics_file: ExtData/optics/opticsBands_SU.v1_3.RRTMG.nc

 aerosol_monochromatic_optics_file: ExtData/monochromatic/optics_SU.v1_3.nc
-aerosol_monochromatic_optics_wavelength: 4.7e-7 5.5e-7 6.7e-7 8.7e-7
-wavelengths_for_vertically_integrated_aop_in_nm: 470 550 670 870
-n_channels: 4

 nbins: 4
```

**Comment by mathomp4** [comment]
@rmontuoro Interesting. Let me consult with @tclune tomorrow about this. It does look like `n_channels` and `r_channels` are useless, but I'm not sure about the other bits. I'll talk with him.

**Review by rmontuoro — APPROVED** [review]
Looks good.

**Comment by mathomp4** [comment]
All of this was done by @pcolarco in the current `develop`. Closing.

**Pull request closed without merging**
